general {
    hide_cursor = true
    font_family = JetBrainsMono Nerd Font
}

background {
    color = rgba(13,17,27,1.0)
    monitor =
    path = ~/.config/hypr/img/wallpaper.png
    blur_passes = 3
    blur_size = 8
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M:%S"
    color = rgba(255,255,255,1.0)
    font_size = 64
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 3
    inner_color = rgba(26,35,51,1.0)
    outer_color = rgba(197,155,130,1.0)
    font_color = rgba(255,255,255,1.0)
    font_size = 24
    placeholder_text = Passwort
    position = 0, -100
    halign = center
    valign = center
}